---
- name: Instalación del entorno de pruebas de la validadora.
  hosts: all
  sudo: true
  tasks:
    - name: Start etcd
      service: name=etcd.service state=started

    - name: Install docker-py
      pip: name=docker-py

    - name: pull arangodb
      docker:
        docker_api_version: 1.15
        name: arangodb
        image: arangodb
        state: present
    
